namespace ImageUtil
{
    public class MetaTags
    {
        public static readonly HashSet<string> Tags = new HashSet<string>
        {
            "tagme",
            "translation request",
            "check translation",
            "commentary request",
            "check commentary",
            "source request",
            "check source",
            "artist request",
            "check artist",
            "copyright request",
            "check copyright",
            "character request",
            "check character",
            "annotation request",
            "check annotation",
            "weapon request",
            "check weapon",
            "skeb commission",
            "pixiv commission",
            "vgen commission",
            "fantia commission",
            "skima commission",
            "bilibili commission",
            "alternate language",
            "translated",
            "hard-translated",
            "partially translated",
            "poorly translated",
            "translation note",
            "commentary",
            "partial commentary",
            "commentary typo",
            "collaboration",
            "commission",
            "commissioner upload",
            "annotated",
            "partially annotated",
            "reverse translation",
            "gift art",
            "making-of",
            "making-of available",
            "video available",
            "completion time",
            "textless version",
            "download link",
            "psd available",
            "pdf available",
            "zip available",
            "check medium",
            "bad id",
            "bad pixiv id",
            "bad twitter id",
            "bad tumblr id",
            "bad deviantart id",
            "bad nicoseiga id",
            "bad drawr id",
            "bad nijie id",
            "bad yandere id",
            "bad artstation id",
            "bad hentai-foundry id",
            "bad instagram id",
            "bad bcy id",
            "bad lofter id",
            "bad weibo id",
            "bad fantia id",
            "bad drawcrowd id",
            "bad tinami id",
            "bad poipiku id",
            "bad fanbox id",
            "bad newgrounds id",
            "bad cghub id",
            "bad google+ id",
            "bad e-hentai id",
            "bad pawoo id",
            "bad patreon id",
            "bad imgur id",
            "bad ci-en id",
            "bad dropbox id",
            "bad artstreet id",
            "bad blogpost id",
            "bad bilibili id",
            "bad cgsociety id",
            "bad photobucket id",
            "bad youtube id",
            "bad behance id",
            "bad miiverse id",
            "bad vkontakte id",
            "bad fandom id",
            "bad pinterest id",
            "bad facebook id",
            "bad skeb id",
            "bad baraag id",
            "bad booth id",
            "bad reddit id",
            "bad picasa id",
            "bad privatter id",
            "bad inkbunny id",
            "bad mihuashi id",
            "bad misskey.io id",
            "bad furaffinity id",
            "bad pillowfort id",
            "bad stash id",
            "bad baidu id",
            "bad drawtwit id",
            "bad foundation id",
            "bad postype id",
            "bad superrare id",
            "bad link",
            "bad source",
            "source mismatch",
            "multiple sources",
            "non-web source",
            "archived source",
            "imageboard desourced",
            "inactive account",
            "protected link",
            "second-party source",
            "third-party source",
            "resolution mismatch",
            "source smaller",
            "source larger",
            "video crop",
            "image sample",
            "pixiv sample",
            "twitter sample",
            "nicoseiga sample",
            "tinami sample",
            "tumblr sample",
            "deviantart sample",
            "artstation sample",
            "drawcrowd sample",
            "yandere sample",
            "cleaned",
            "cropped",
            "colorized",
            "paintschainer",
            "recolored",
            "adjusted color balance",
            "noise reduction",
            "resized",
            "upscaled",
            "aliasing",
            "downscaled",
            "waifu2x",
            "third-party edit",
            "detexted",
            "nude filter",
            "decensored",
            "headshop",
            "third-party watermark",
            "hard-translated",
            "fake translation",
            "hard-translated",
            "machine translated",
            "poorly translated",
            "has bad revision",
            "has artifacted revision",
            "has censored revision",
            "has cropped revision",
            "has downscaled revision",
            "has lossy revision",
            "has watermarked revision",
            "bad aspect ratio",
            "reversed",
            "rotated",
            "exif rotation",
            "stitched",
            "poorly stitched",
            "webp-to-png conversion",
            "webp-to-jpg conversion",
            "ugoira conversion",
            "flash conversion",
            "vector trace",
            "extraction",
            "lowres",
            "highres",
            "absurdres",
            "incredibly absurdres",
            "animated",
            "animated png",
            "animated gif",
            "fast animated gif",
            "flash",
            "flash 9",
            "interactive",
            "flash game",
            "ruffle compatible",
            "video",
            "high efficiency video coding",
            "low bitrate",
            "ugoira",
            "sound",
            "audible music",
            "audible speech",
            "volume warning",
            "looping animation",
            "non-repeating animation",
            "roulette animation",
            "alpha transparency",
            "archived file",
            "hidden file",
            "open in winamp",
            "alt text",
            "open in internet explorer",
            "thumbnail surprise",
            "exif thumbnail surprise",
            "jpeg artifacts",
            "gif artifacts",
            "tall image",
            "wide image",
            "wallpaper forced",
            "twitter banner",
            "lossy-lossless",
            "lossless-lossy",
            "low frame rate",
            "missing file",
            "corrupted file",
            "corrupted flash",
            "corrupted metadata",
            "missing thumbnail",
            "solid color thumbnail",
            "epilepsy warning",
            "md5 mismatch",
            "ai-generated",
            "ai-assisted",
            "duplicate",
            "pixel-perfect duplicate",
            "derivative work",
            "reference photo / photo-referenced",
            "anime screencap",
            "game screenshot",
            "screenshot",
            "redrawn",
            "album cover redraw",
            "comic panel redraw",
            "screencap redraw",
            "eyecatch",
            "end card",
            "game cg",
            "novel illustration",
            "official art",
            "game model",
            "key visual",
            "promotional art",
            "production art",
            "animatic",
            "disc menu",
            "cd(source)",
            "spoilers",
            "check spoilers",
            "paid reward",
            "patreon reward",
            "enty reward",
            "fantia reward",
            "fanbox reward",
            "gumroad reward",
            "paid reward available",
            "line sticker available",
            "scan",
            "color halftone",
            "magazine scan",
            "scan artifacts",
            "scan dust",
            "self scan",
            "bleed through",
            "binding discoloration",
            "fixed",
            "avatar generator",
            "off - topic",
            "jav",
            "self - upload",
            "revision",
            "variant set"
        };
    }
}
