/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SdWebUiApi.Client.OpenAPIDateConverter;

namespace SdWebUiApi.Model
{
    /// <summary>
    /// BodyRembgRemoveRembgPost
    /// </summary>
    [DataContract(Name = "Body_rembg_remove_rembg_post")]
    public partial class BodyRembgRemoveRembgPost : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyRembgRemoveRembgPost" /> class.
        /// </summary>
        /// <param name="inputImage">inputImage (default to &quot;&quot;).</param>
        /// <param name="model">model (default to &quot;u2net&quot;).</param>
        /// <param name="returnMask">returnMask (default to false).</param>
        /// <param name="alphaMatting">alphaMatting (default to false).</param>
        /// <param name="alphaMattingForegroundThreshold">alphaMattingForegroundThreshold (default to 240).</param>
        /// <param name="alphaMattingBackgroundThreshold">alphaMattingBackgroundThreshold (default to 10).</param>
        /// <param name="alphaMattingErodeSize">alphaMattingErodeSize (default to 10).</param>
        public BodyRembgRemoveRembgPost(string inputImage = @"", string model = @"u2net", bool returnMask = false, bool alphaMatting = false, int alphaMattingForegroundThreshold = 240, int alphaMattingBackgroundThreshold = 10, int alphaMattingErodeSize = 10)
        {
            // use default value if no "inputImage" provided
            this.InputImage = inputImage ?? @"";
            // use default value if no "model" provided
            this.Model = model ?? @"u2net";
            this.ReturnMask = returnMask;
            this.AlphaMatting = alphaMatting;
            this.AlphaMattingForegroundThreshold = alphaMattingForegroundThreshold;
            this.AlphaMattingBackgroundThreshold = alphaMattingBackgroundThreshold;
            this.AlphaMattingErodeSize = alphaMattingErodeSize;
        }

        /// <summary>
        /// Gets or Sets InputImage
        /// </summary>
        [DataMember(Name = "input_image", EmitDefaultValue = false)]
        public string InputImage { get; set; }

        /// <summary>
        /// Gets or Sets Model
        /// </summary>
        [DataMember(Name = "model", EmitDefaultValue = false)]
        public string Model { get; set; }

        /// <summary>
        /// Gets or Sets ReturnMask
        /// </summary>
        [DataMember(Name = "return_mask", EmitDefaultValue = true)]
        public bool ReturnMask { get; set; }

        /// <summary>
        /// Gets or Sets AlphaMatting
        /// </summary>
        [DataMember(Name = "alpha_matting", EmitDefaultValue = true)]
        public bool AlphaMatting { get; set; }

        /// <summary>
        /// Gets or Sets AlphaMattingForegroundThreshold
        /// </summary>
        [DataMember(Name = "alpha_matting_foreground_threshold", EmitDefaultValue = false)]
        public int AlphaMattingForegroundThreshold { get; set; }

        /// <summary>
        /// Gets or Sets AlphaMattingBackgroundThreshold
        /// </summary>
        [DataMember(Name = "alpha_matting_background_threshold", EmitDefaultValue = false)]
        public int AlphaMattingBackgroundThreshold { get; set; }

        /// <summary>
        /// Gets or Sets AlphaMattingErodeSize
        /// </summary>
        [DataMember(Name = "alpha_matting_erode_size", EmitDefaultValue = false)]
        public int AlphaMattingErodeSize { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BodyRembgRemoveRembgPost {\n");
            sb.Append("  InputImage: ").Append(InputImage).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  ReturnMask: ").Append(ReturnMask).Append("\n");
            sb.Append("  AlphaMatting: ").Append(AlphaMatting).Append("\n");
            sb.Append("  AlphaMattingForegroundThreshold: ").Append(AlphaMattingForegroundThreshold).Append("\n");
            sb.Append("  AlphaMattingBackgroundThreshold: ").Append(AlphaMattingBackgroundThreshold).Append("\n");
            sb.Append("  AlphaMattingErodeSize: ").Append(AlphaMattingErodeSize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
