/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SdWebUpApi.Client.OpenAPIDateConverter;

namespace SdWebUpApi.Model
{
    /// <summary>
    /// ExtrasBatchImagesResponse
    /// </summary>
    [DataContract(Name = "ExtrasBatchImagesResponse")]
    public partial class ExtrasBatchImagesResponse : IEquatable<ExtrasBatchImagesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtrasBatchImagesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExtrasBatchImagesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtrasBatchImagesResponse" /> class.
        /// </summary>
        /// <param name="htmlInfo">A series of HTML tags containing the process info. (required).</param>
        /// <param name="images">The generated images in base64 format. (required).</param>
        public ExtrasBatchImagesResponse(string htmlInfo = default(string), List<string> images = default(List<string>))
        {
            // to ensure "htmlInfo" is required (not null)
            if (htmlInfo == null)
            {
                throw new ArgumentNullException("htmlInfo is a required property for ExtrasBatchImagesResponse and cannot be null");
            }
            this.HtmlInfo = htmlInfo;
            // to ensure "images" is required (not null)
            if (images == null)
            {
                throw new ArgumentNullException("images is a required property for ExtrasBatchImagesResponse and cannot be null");
            }
            this.Images = images;
        }

        /// <summary>
        /// A series of HTML tags containing the process info.
        /// </summary>
        /// <value>A series of HTML tags containing the process info.</value>
        [DataMember(Name = "html_info", IsRequired = true, EmitDefaultValue = true)]
        public string HtmlInfo { get; set; }

        /// <summary>
        /// The generated images in base64 format.
        /// </summary>
        /// <value>The generated images in base64 format.</value>
        [DataMember(Name = "images", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Images { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExtrasBatchImagesResponse {\n");
            sb.Append("  HtmlInfo: ").Append(HtmlInfo).Append("\n");
            sb.Append("  Images: ").Append(Images).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExtrasBatchImagesResponse);
        }

        /// <summary>
        /// Returns true if ExtrasBatchImagesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ExtrasBatchImagesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExtrasBatchImagesResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.HtmlInfo == input.HtmlInfo ||
                    (this.HtmlInfo != null &&
                    this.HtmlInfo.Equals(input.HtmlInfo))
                ) && 
                (
                    this.Images == input.Images ||
                    this.Images != null &&
                    input.Images != null &&
                    this.Images.SequenceEqual(input.Images)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HtmlInfo != null)
                {
                    hashCode = (hashCode * 59) + this.HtmlInfo.GetHashCode();
                }
                if (this.Images != null)
                {
                    hashCode = (hashCode * 59) + this.Images.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
