/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SdWebUiApi.Client.OpenAPIDateConverter;

namespace SdWebUiApi.Model
{
    /// <summary>
    /// PNGInfoResponse
    /// </summary>
    [DataContract(Name = "PNGInfoResponse")]
    public partial class PNGInfoResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PNGInfoResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PNGInfoResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PNGInfoResponse" /> class.
        /// </summary>
        /// <param name="info">A string with the parameters used to generate the image (required).</param>
        /// <param name="items">An object containing all the info the image had (required).</param>
        public PNGInfoResponse(string info = default(string), Object items = default(Object))
        {
            // to ensure "info" is required (not null)
            if (info == null)
            {
                throw new ArgumentNullException("info is a required property for PNGInfoResponse and cannot be null");
            }
            this.Info = info;
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for PNGInfoResponse and cannot be null");
            }
            this.Items = items;
        }

        /// <summary>
        /// A string with the parameters used to generate the image
        /// </summary>
        /// <value>A string with the parameters used to generate the image</value>
        [DataMember(Name = "info", IsRequired = true, EmitDefaultValue = true)]
        public string Info { get; set; }

        /// <summary>
        /// An object containing all the info the image had
        /// </summary>
        /// <value>An object containing all the info the image had</value>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public Object Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PNGInfoResponse {\n");
            sb.Append("  Info: ").Append(Info).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
