/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SdWebUiApi.Client.OpenAPIDateConverter;

namespace SdWebUiApi.Model
{
    /// <summary>
    /// ProgressRequest
    /// </summary>
    [DataContract(Name = "ProgressRequest")]
    public partial class ProgressRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProgressRequest" /> class.
        /// </summary>
        /// <param name="idTask">id of the task to get progress for.</param>
        /// <param name="idLivePreview">id of last received last preview image (default to -1).</param>
        /// <param name="livePreview">boolean flag indicating whether to include the live preview image (default to true).</param>
        public ProgressRequest(string idTask = default(string), int idLivePreview = -1, bool livePreview = true)
        {
            this.IdTask = idTask;
            this.IdLivePreview = idLivePreview;
            this.LivePreview = livePreview;
        }

        /// <summary>
        /// id of the task to get progress for
        /// </summary>
        /// <value>id of the task to get progress for</value>
        [DataMember(Name = "id_task", EmitDefaultValue = false)]
        public string IdTask { get; set; }

        /// <summary>
        /// id of last received last preview image
        /// </summary>
        /// <value>id of last received last preview image</value>
        [DataMember(Name = "id_live_preview", EmitDefaultValue = false)]
        public int IdLivePreview { get; set; }

        /// <summary>
        /// boolean flag indicating whether to include the live preview image
        /// </summary>
        /// <value>boolean flag indicating whether to include the live preview image</value>
        [DataMember(Name = "live_preview", EmitDefaultValue = true)]
        public bool LivePreview { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProgressRequest {\n");
            sb.Append("  IdTask: ").Append(IdTask).Append("\n");
            sb.Append("  IdLivePreview: ").Append(IdLivePreview).Append("\n");
            sb.Append("  LivePreview: ").Append(LivePreview).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
