/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SdWebUpApi.Client.OpenAPIDateConverter;

namespace SdWebUpApi.Model
{
    /// <summary>
    /// ResetBody
    /// </summary>
    [DataContract(Name = "ResetBody")]
    public partial class ResetBody : IEquatable<ResetBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResetBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResetBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResetBody" /> class.
        /// </summary>
        /// <param name="sessionHash">sessionHash (required).</param>
        /// <param name="fnIndex">fnIndex (required).</param>
        public ResetBody(string sessionHash = default(string), int fnIndex = default(int))
        {
            // to ensure "sessionHash" is required (not null)
            if (sessionHash == null)
            {
                throw new ArgumentNullException("sessionHash is a required property for ResetBody and cannot be null");
            }
            this.SessionHash = sessionHash;
            this.FnIndex = fnIndex;
        }

        /// <summary>
        /// Gets or Sets SessionHash
        /// </summary>
        [DataMember(Name = "session_hash", IsRequired = true, EmitDefaultValue = true)]
        public string SessionHash { get; set; }

        /// <summary>
        /// Gets or Sets FnIndex
        /// </summary>
        [DataMember(Name = "fn_index", IsRequired = true, EmitDefaultValue = true)]
        public int FnIndex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResetBody {\n");
            sb.Append("  SessionHash: ").Append(SessionHash).Append("\n");
            sb.Append("  FnIndex: ").Append(FnIndex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResetBody);
        }

        /// <summary>
        /// Returns true if ResetBody instances are equal
        /// </summary>
        /// <param name="input">Instance of ResetBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResetBody input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SessionHash == input.SessionHash ||
                    (this.SessionHash != null &&
                    this.SessionHash.Equals(input.SessionHash))
                ) && 
                (
                    this.FnIndex == input.FnIndex ||
                    this.FnIndex.Equals(input.FnIndex)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SessionHash != null)
                {
                    hashCode = (hashCode * 59) + this.SessionHash.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.FnIndex.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
