/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SdWebUiApi.Client.OpenAPIDateConverter;

namespace SdWebUiApi.Model
{
    /// <summary>
    /// ResetBody
    /// </summary>
    [DataContract(Name = "ResetBody")]
    public partial class ResetBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResetBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResetBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResetBody" /> class.
        /// </summary>
        /// <param name="sessionHash">sessionHash (required).</param>
        /// <param name="fnIndex">fnIndex (required).</param>
        public ResetBody(string sessionHash = default(string), int fnIndex = default(int))
        {
            // to ensure "sessionHash" is required (not null)
            if (sessionHash == null)
            {
                throw new ArgumentNullException("sessionHash is a required property for ResetBody and cannot be null");
            }
            this.SessionHash = sessionHash;
            this.FnIndex = fnIndex;
        }

        /// <summary>
        /// Gets or Sets SessionHash
        /// </summary>
        [DataMember(Name = "session_hash", IsRequired = true, EmitDefaultValue = true)]
        public string SessionHash { get; set; }

        /// <summary>
        /// Gets or Sets FnIndex
        /// </summary>
        [DataMember(Name = "fn_index", IsRequired = true, EmitDefaultValue = true)]
        public int FnIndex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResetBody {\n");
            sb.Append("  SessionHash: ").Append(SessionHash).Append("\n");
            sb.Append("  FnIndex: ").Append(FnIndex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
