/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SdWebUiApi.Client.OpenAPIDateConverter;

namespace SdWebUiApi.Model
{
    /// <summary>
    /// ScriptInfo
    /// </summary>
    [DataContract(Name = "ScriptInfo")]
    public partial class ScriptInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScriptInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScriptInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScriptInfo" /> class.
        /// </summary>
        /// <param name="name">Script name.</param>
        /// <param name="isAlwayson">Flag specifying whether this script is an alwayson script.</param>
        /// <param name="isImg2img">Flag specifying whether this script is an img2img script.</param>
        /// <param name="args">List of script&#39;s arguments (required).</param>
        public ScriptInfo(string name = default(string), bool isAlwayson = default(bool), bool isImg2img = default(bool), List<ScriptArg> args = default(List<ScriptArg>))
        {
            // to ensure "args" is required (not null)
            if (args == null)
            {
                throw new ArgumentNullException("args is a required property for ScriptInfo and cannot be null");
            }
            this.Args = args;
            this.Name = name;
            this.IsAlwayson = isAlwayson;
            this.IsImg2img = isImg2img;
        }

        /// <summary>
        /// Script name
        /// </summary>
        /// <value>Script name</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Flag specifying whether this script is an alwayson script
        /// </summary>
        /// <value>Flag specifying whether this script is an alwayson script</value>
        [DataMember(Name = "is_alwayson", EmitDefaultValue = true)]
        public bool IsAlwayson { get; set; }

        /// <summary>
        /// Flag specifying whether this script is an img2img script
        /// </summary>
        /// <value>Flag specifying whether this script is an img2img script</value>
        [DataMember(Name = "is_img2img", EmitDefaultValue = true)]
        public bool IsImg2img { get; set; }

        /// <summary>
        /// List of script&#39;s arguments
        /// </summary>
        /// <value>List of script&#39;s arguments</value>
        [DataMember(Name = "args", IsRequired = true, EmitDefaultValue = true)]
        public List<ScriptArg> Args { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScriptInfo {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsAlwayson: ").Append(IsAlwayson).Append("\n");
            sb.Append("  IsImg2img: ").Append(IsImg2img).Append("\n");
            sb.Append("  Args: ").Append(Args).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
