/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SdWebUpApi.Client.OpenAPIDateConverter;

namespace SdWebUpApi.Model
{
    /// <summary>
    /// SDVaeItem
    /// </summary>
    [DataContract(Name = "SDVaeItem")]
    public partial class SDVaeItem : IEquatable<SDVaeItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SDVaeItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SDVaeItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SDVaeItem" /> class.
        /// </summary>
        /// <param name="modelName">modelName (required).</param>
        /// <param name="filename">filename (required).</param>
        public SDVaeItem(string modelName = default(string), string filename = default(string))
        {
            // to ensure "modelName" is required (not null)
            if (modelName == null)
            {
                throw new ArgumentNullException("modelName is a required property for SDVaeItem and cannot be null");
            }
            this.ModelName = modelName;
            // to ensure "filename" is required (not null)
            if (filename == null)
            {
                throw new ArgumentNullException("filename is a required property for SDVaeItem and cannot be null");
            }
            this.Filename = filename;
        }

        /// <summary>
        /// Gets or Sets ModelName
        /// </summary>
        [DataMember(Name = "model_name", IsRequired = true, EmitDefaultValue = true)]
        public string ModelName { get; set; }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [DataMember(Name = "filename", IsRequired = true, EmitDefaultValue = true)]
        public string Filename { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SDVaeItem {\n");
            sb.Append("  ModelName: ").Append(ModelName).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SDVaeItem);
        }

        /// <summary>
        /// Returns true if SDVaeItem instances are equal
        /// </summary>
        /// <param name="input">Instance of SDVaeItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SDVaeItem input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ModelName == input.ModelName ||
                    (this.ModelName != null &&
                    this.ModelName.Equals(input.ModelName))
                ) && 
                (
                    this.Filename == input.Filename ||
                    (this.Filename != null &&
                    this.Filename.Equals(input.Filename))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ModelName != null)
                {
                    hashCode = (hashCode * 59) + this.ModelName.GetHashCode();
                }
                if (this.Filename != null)
                {
                    hashCode = (hashCode * 59) + this.Filename.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
