/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SdWebUpApi.Client.OpenAPIDateConverter;

namespace SdWebUpApi.Model
{
    /// <summary>
    /// UpscalerItem
    /// </summary>
    [DataContract(Name = "UpscalerItem")]
    public partial class UpscalerItem : IEquatable<UpscalerItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpscalerItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpscalerItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpscalerItem" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="modelName">modelName.</param>
        /// <param name="modelPath">modelPath.</param>
        /// <param name="modelUrl">modelUrl.</param>
        /// <param name="scale">scale.</param>
        public UpscalerItem(string name = default(string), string modelName = default(string), string modelPath = default(string), string modelUrl = default(string), decimal scale = default(decimal))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for UpscalerItem and cannot be null");
            }
            this.Name = name;
            this.ModelName = modelName;
            this.ModelPath = modelPath;
            this.ModelUrl = modelUrl;
            this.Scale = scale;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ModelName
        /// </summary>
        [DataMember(Name = "model_name", EmitDefaultValue = false)]
        public string ModelName { get; set; }

        /// <summary>
        /// Gets or Sets ModelPath
        /// </summary>
        [DataMember(Name = "model_path", EmitDefaultValue = false)]
        public string ModelPath { get; set; }

        /// <summary>
        /// Gets or Sets ModelUrl
        /// </summary>
        [DataMember(Name = "model_url", EmitDefaultValue = false)]
        public string ModelUrl { get; set; }

        /// <summary>
        /// Gets or Sets Scale
        /// </summary>
        [DataMember(Name = "scale", EmitDefaultValue = false)]
        public decimal Scale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpscalerItem {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ModelName: ").Append(ModelName).Append("\n");
            sb.Append("  ModelPath: ").Append(ModelPath).Append("\n");
            sb.Append("  ModelUrl: ").Append(ModelUrl).Append("\n");
            sb.Append("  Scale: ").Append(Scale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpscalerItem);
        }

        /// <summary>
        /// Returns true if UpscalerItem instances are equal
        /// </summary>
        /// <param name="input">Instance of UpscalerItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpscalerItem input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ModelName == input.ModelName ||
                    (this.ModelName != null &&
                    this.ModelName.Equals(input.ModelName))
                ) && 
                (
                    this.ModelPath == input.ModelPath ||
                    (this.ModelPath != null &&
                    this.ModelPath.Equals(input.ModelPath))
                ) && 
                (
                    this.ModelUrl == input.ModelUrl ||
                    (this.ModelUrl != null &&
                    this.ModelUrl.Equals(input.ModelUrl))
                ) && 
                (
                    this.Scale == input.Scale ||
                    this.Scale.Equals(input.Scale)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.ModelName != null)
                {
                    hashCode = (hashCode * 59) + this.ModelName.GetHashCode();
                }
                if (this.ModelPath != null)
                {
                    hashCode = (hashCode * 59) + this.ModelPath.GetHashCode();
                }
                if (this.ModelUrl != null)
                {
                    hashCode = (hashCode * 59) + this.ModelUrl.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Scale.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
